insert into t_categorie values
(1, 'Reve', "Le rêve désigne un ensemble de phénomènes psychiques éprouvés au cours du sommeil. Au cours de l'Histoire, différents domaines de la connaissance se sont intéressés au rêve, y cherchant du sens ou une fonction. Au réveil, le souvenir du rêve est souvent lacunaire, parfois inexistant. Il est cependant possible d'entraîner la remémoration onirique. Les rêves sont les plus élaboés pendant les phases de sommeil paradoxal.", 'Ange.jpg');
insert into t_categorie values
(2, 'Cauchemar', "Un cauchemar cause une forte émotion négative, le plus communément de la peur ou de l'horreur, mais également du désespoir, de l'anxiété ou une grande tristesse. Les cauchemar peuvent impliquer des situations de danger, de mal-être psychologiques ou physiques, de terreur. Suite à un cauchemar l'on se reveil souvent dans un état de détresse, et on peut avoir du mal à retrouver le sommeil durant un certain temps." ,'Demond.jpg');

insert into t_article values
(1, 'Alice au pays des merveille', "Alice, désormais âgée de 19 ans, retourne dans le monde fantastique qu'elle a découvert quand elle était enfant. Elle y retrouve ses amis le Lapin Blanc, Bonnet Blanc et Blanc Bonnet, le Loir, la Chenille, le Chat du Cheshire et, bien entendu, le Chapelier Fou. Alice s'embarque alors dans une aventure extraordinaire où elle accomplira son destin : mettre fin au règne de terreur de la Reine Rouge. ",1,'Alice-aux-pays-des-merveilles.jpg',19);
insert into t_article values
(2, 'Cendrillon', "Le père d’Ella, un marchand, s’est remarié après la mort tragique de la mère de la jeune fille. Pour l’amour de son père, Ella accueille à bras ouverts sa nouvelle belle-mère et les filles de celle-ci, Anastasie et Javotte. Mais lorsque le père d’Ella meurt à son tour, la jeune fille se retrouve à la merci de sa nouvelle famille, jalouse et cruelle. Les trois méchantes femmes font d’elle leur servante, et la surnomment avec mépris Cendrillon parce qu’elle est toujours couverte de cendres. Pourtant, malgré la cruauté dont elle est victime, Ella est déterminée à respecter la promesse faite à sa mère avant de mourir : elle sera courageuse et bonne. Elle ne se laissera aller ni au désespoir, ni au mépris envers ceux qui la maltraitent. Un jour, Ella rencontre un beau jeune homme dans la forêt. Ignorant qu’il s’agit d’un prince, elle le croit employé au palais. Ella a le sentiment d’avoir trouvé l’âme soeur. Une lueur d’espoir brûle dans son coeur, car toutes les jeunes filles du pays ont été invitées à assister à un bal au palais. Espérant y rencontrer à nouveau le charmant Kit, Ella attend avec impatience de se rendre à la fête. Hélas, sa belle-mère lui défend d’y assister et réduit sa robe en pièces… Pendant ce temps, le Grand Duc complote avec la méchante belle-mère pour empêcher le Prince de retrouver celle qu’il aime... Heureusement, comme dans tout bon conte de fées, la chance finira par sourire à Ella : une vieille mendiante fait son apparition, et à l’aide d’une citrouille et de quelques souris, elle va changer le destin de la jeune fille… ",1,'cendrillon.jpg',19);
insert into t_article values
(3, 'Le Balle des 12 princesses', "Douze princesses plus belles les unes que les autres dorment dans douze lits qui sont dans la même chambre. Chaque nuit leur porte est fermée à clé. Mais, au matin, leurs souliers sont usés comme si elles avaient dansé toute la nuit. Le roi, perplexe, promet son royaume et la main d'une de ses filles à l'homme qui trouvera le secret des princesses en trois jours et trois nuits ; mais ceux qui échoueront seront mis à mort. Un soldat d'âge mûr qui rentre de la guerre se rend au château du roi après que plusieurs princes aient déjà fait de vaines tentatives. En traversant les bois, il rencontre une vieille femme qui lui confie une cape d’invisibilité, lui conseille de ne rien manger ou boire qui lui sera donné par les princesses et de faire semblant de dormir jusqu'à leur départ. Le soldat est bien reçu au palais comme tous ceux qui l'ont précédé, et en effet, le soir venu, l'aînée des princesses lui porte une coupe de vin. Le soldat, se rappelant la recommandation de la vieille dame, la vide secrètement et fait semblant de ronfler fortement. Les princesses, certaines que le soldat dort, s'habillent de belles robes et sortent de leur chambre par une trappe dans le plancher. Voyant cela, le soldat revêt sa cape d'invisibilité et les suit. Il marche sur la robe de la plus jeune princesse, dont les cris d'alarme ne sont pas écoutés par la plus âgée des sœurs. Le passage les mène à trois bosquets, l'un aux feuillages d'argent, le second d'or, et le troisième de diamant.Le soldat ayant besoin de preuves prélève un rameau de chacun. Ils marchent jusqu'à un lac où douze bateaux attendent avec douze princes. Chaque princesse monte dans l'un d'eux, le soldat embarque avec la plus jeune. Le prince rame lentement, ne se rendant pas compte du poids supplémentaire du soldat. La plus jeune princesse se plaint de sa lenteur, ne sachant pas que le soldat est dans le bateau. De l'autre côté du lac est un château, où les princesses dansent toute la nuit.Elles dansent jusqu'à ce que leur souliers soient trop usés, les obligeant à partir. Cette étrange aventure se reproduit les seconde et troisième nuits, et tout recommence de la même façon, sauf que la troisième nuit le soldat emporte une coupe en or comme preuve de son passage. Quand vient le moment de révéler le secret des princesses, il vient auprès du roi avec les trois brindilles et la coupe, et raconte au roi ce qu'il a vu. Les princesses comprennent que nier est inutile et confessent la vérité. Le soldat choisit l'aînée des princesses pour femme puisqu'il n'est plus tout jeune homme, et devient hériter du roi.",1,'douze.jpg',19);
insert into t_article values
(7, 'Le marchand de sable', "Là-haut, quelque part sous les étoiles…Se trouve un pays merveilleux, dont le ciel est fait de nuages mauve et rose, les plaines de nuages blancs, les chemin de nuages gris et les lacs de nuages bleus. Et ce pays recèle un endroit unique et merveilleux. On y accède par un splendide portail de cristal, au fronton duquel on peut lire en lettres d’or : « CARRIERE DE SABLE MAGIQUE ». Dès que l’on passe ce portail, on aperçoit à perte de vue des tas et des tas de sable fin, presque impalpable. On dirait de la poudre d’or. Et si sur la terre on n’en a jamais vu de pareil, tous un jour où l’autre nous l’avons cependant senti. « Pas possible ! » direz-vous. Eh bien si ! Car il faut vous dire que ce sable n’est pas un sable ordinaire : comme l’indique l’inscription du portail, c’est un sable magique et seul en a l’usage un bien mystérieux personnage. On l’appelle LE MARCHAND DE SABLE. ET nous, nous vous proposons une petit poignet de se sable a oser sur les yeux de vos enfants.",1,'marchand.png',19);


insert into t_article values
(4, "Visite du royaume d'hades", "Le royaume d’Hadès est l’endroit où toutes les âmes vont pour être jugées après la mort. Elles sont retenues comme des ombres sans force ni sentiment, pure présence d’un passé à jamais aboli, et qui peuvent reprendre vie quand on les évoque, en général par une libation de sang à même le sol. Serez vous près a visiter votre futur résidence?",2,'tenebres.jpg',19);
insert into t_article values
(5, "Rencontre avec un chien à trois tête", "Chacune des têtes n'aurait d'appétit que pour la viande vivante et autorise donc les esprits des morts à entrer dans le monde souterrain, mais les empêche d'en sortir. Cerbère et le fidèle gardien d'Hadès, gardant les portes donnant sur le monde souterrain. Plusieurs héros ont déja réussi à déjouer sa vigilance, voire à le vaincre. Orphée, décidé à sortir des Enfers sa femme Eurydice, morte d’une morsure de vipère, parvient à le charmer en chantant et en jouant de sa lyre. Et vous etes vous près à le défier dans vos cauchemar les plus fou? Sensation garantie.",2,'cerbar.jpg',19);
insert into t_article values
(6, "Pitch", "Ce cauchemar va transformer tous vos rêves en vos pires cauchemars. Etes vous vraiment près a passer une nuit entier sans faire un seul reve? Si oui ce cauchemar est fait pour vous, lancez vous, vous ne serais pas dessus.",2,'pitch.jpg',19);


insert into t_user values
(1, 'admin', 'nom de famille','adresse','38530','Pontcharra','matthieu@gmail.com', 'gqeuP4YJ8hU3ZqGwGikB6+rcZBqefVy+7hTLQkOD+jwVkp4fkS7/gr1rAQfn9VUKWc7bvOD7OsXrQQN5KGHbfg==', 'EDDsl&fBCJB|a5XUtAlnQN8', 'ROLE_ADMIN');

insert into t_comment values
(1, "J'AI TROP TROP BIEN DORMI UN TRUC DE OUF!!!!!!!!!!", 1, 1);
insert into t_comment values
(2, "Ma petit a fait sa premiere nuit. Enfin du repos pour moi!", 1, 1);

